MicrosoftDocs/terminal

TerminalDocs/tutorials/powerline-setup.md

Addressing issue: https://github.com/MicrosoftDocs/terminal/issues/17
Thanks @stuarthallows!

Add font designation to Powerline setup tutorial

---

TerminalDocs/index.md

Default shortcut to open a new tab should be `ctrl-shift-t`
Currently it is specified as `ctrl-t`

Default shortcut to open a new tab should be ctrl-shift-t

---

TerminalDocs/customize-settings/color-schemes.md

The example config contains an invalid color for selectionBackground which results in a parse error when pasting it into settings.json. To fix it, we can just fill it with 'white'.

Set a background to make example config valid

---

TerminalDocs/cascadia-code.md
TerminalDocs/command-line-arguments.md
TerminalDocs/customize-settings/color-schemes.md
TerminalDocs/get-started.md
TerminalDocs/index.md
TerminalDocs/panes.md
TerminalDocs/troubleshooting.md

Command line should be hyphened when used as an adjective:
https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/c/command-line

add hyphen to command line

---

TerminalDocs/customize-settings/color-schemes.md

These themes are bad, and we feel bad for shipping them. They're still in the code, but by removing them from the docs, hopefully fewer people will make the mistake of using these themes.

Remove "Solarized" themes from the docs

---

TerminalDocs/customize-settings/global-settings.md
TerminalDocs/customize-settings/key-bindings.md

Does what it says.
See also https://github.com/microsoft/terminal/pull/6903

Add always on top mode to the keybindings, globals

---

TerminalDocs/customize-settings/global-settings.md

Pursuant to microsoft/terminal#6891.

Remove rowsToScroll from the global settings section

---

TerminalDocs/customize-settings/global-settings.md

I added a new section called _Paste warnings_ with the new settings
from this PR: https://github.com/microsoft/terminal/pull/6631.
I also added a little bit of explanation about you would want these
warnings to be enabled.
**DO NOT MERGE FOR NOW because the corresponding PR on the
Windows Terminal repository is not merged yet.**

Add settings for paste warnings

---

TerminalDocs/troubleshooting.md

- Removed comma at startingDirectory parameter in sample
Belongs to issue #61

Fixed "Set your WSL distribution to start in the home"

---

TerminalDocs/customize-settings/key-bindings.md

`sendInput` was added in: https://github.com/microsoft/terminal/pull/7249

Add documentation for the sendInput command

---

TerminalDocs/customize-settings/global-settings.md
TerminalDocs/customize-settings/key-bindings.md

Keybinding docs for the Advanced Tab Switcher - microsoft/terminal#6732
This should probably _not_ go into master but into one of the release branches 😄 
edit: still need to update after 7321 goes in

Add keybinding docs for tabSwitcher

---

TerminalDocs/customize-settings/global-settings.md
TerminalDocs/customize-settings/key-bindings.md

I accidentally merged #107 into master, so I'm removing these docs to prevent merge conflicts with the release-1.3 branch. I've moved this content into the cinnamon/release-1.3 branch already.

Remove tabSwitcher docs from master

---

TerminalDocs/customize-settings/key-bindings.md
TerminalDocs/panes.md

Splitting panes always provides panes of the same surface area regardless of direction.
The best geometric description I thought of was "splits along the shorter perpendicular bisector", which is quite precise, but probably a bit too technical for these docs. Apparently "squarest" is a word, though, and it matches intuition if you see the split in action.
I also tried to simplify the description of `auto` and `splitPane`. The latter now has all the values next to each other in one list. If someone were skimming (something I do a lot) the could miss the `auto` value with current wording.
Supersedes https://github.com/microsoft/terminal/pull/5951

Fix error wrt splitting panes

---

TerminalDocs/customize-settings/key-bindings.md

The documentation is not clear that the `Windows` key is not a valid modifier for key bindings. I think people are looking for this when they try to customize their terminal - at least I did and it took me a lot of effort to find that this is not ab option yet.
The corresponding Issue for the feature request is [#3184](https://github.com/microsoft/terminal/issues/3184)

Explicit state that windows key is not supported

---

TerminalDocs/customize-settings/key-bindings.md

Plus was under arrow keys. Moved it to symbols.

Move 'plus' to symbols category

---

TerminalDocs/tutorials/powerline-setup.md

Added a tip on how to support powerline glyphs in VS Code's integrated terminal

Show how to support powerline glyphs in the VS Code terminal

---

TerminalDocs/index.md

In Bash, backticks are used for command substitution. In PowerShell they're escapes.
In Bash, I think it would be:
```bash
wt -p "Command Prompt" \; split-pane -p "Windows PowerShell" \; split-pane -H wsl.exe
```

Fix language indicator

---

TerminalDocs/customize-settings/profile-settings.md

Added documentation to profile-setting.md for the setting "backgroundImage" to accept "DesktopWallpaper" as a way to mimic the desktops wallpaper as the terminals background image.
Documentation for https://github.com/microsoft/terminal/issues/7295
*I am a student and this is my first pull request for Terminal so please give feedback no matter how small. It's the best way I can learn.

Auto detect background image docs

---

TerminalDocs/troubleshooting.md

These are the steps to re-enable the keyboard service, the one that we'll warn about in microsoft/terminal#8095.
🔔 **THERE'S NO `release-1.5` BRANCH YET** 🔔 @cinnamon-msft make sure to fix this before merge

Add troubleshooting tips for the keyboard service dialog 

---

TerminalDocs/customize-settings/profile-settings.md

If the source field specified for custom profile we fail silently. 
Let's start with documenting that this field is not expected in custom profile.
See https://github.com/microsoft/terminal/issues/8333.

Warn to omit source in custom profile declaration

---

TerminalDocs/customize-settings/profile-settings.md

This adds the documentation for the cursor `doubleUnderscore`, as added in [microsoft/terminal#7827](https://github.com/microsoft/terminal/pull/7827).

Add docs for double underscore cursor

---

TerminalDocs/command-line-arguments.md

See implementation: microsoft/terminal#8546

Add docs for `move-focus` subcommand

---

TerminalDocs/customize-settings/actions.md

Documentation for https://github.com/microsoft/terminal/pull/8338

Document moveTab command

---

TerminalDocs/command-palette.md

Documents https://github.com/microsoft/terminal/issues/8322.
Doesn't document "action" launchMode (since it is enabled by default)

Document commandLine launchMode for command palette

---

TerminalDocs/command-line-arguments.md

For some reason they were tagged as bash, which broke highlighting in at least one of them.

command-line-arguments.md: Tag the Command Prompt code blocks

---

TerminalDocs/command-palette.md

in line 98 it's `C:\\path\\to\\icon.png` while in line 115 is a reference to line 98 with `C:\\path\\to\\icon`. So I've added the missing `.png`

fixed typo

---

TerminalDocs/troubleshooting.md

We've had two complaints about this in the span of a week. Maybe we need more documentation?

Add a note about hiding dynamic profiles

---

TerminalDocs/tutorials/ssh.md

This commit clarifies how and where to add a profile in the Windows Terminal `settings.json` and adds a link to relevant terminal docs about profiles. As a new Windows Terminal user, I was unfamiliar with the structure of Windows Terminal profiles. I added a link to other informative doc pages to learn more about how to use profiles.

Clarify adding profile in ssh tutorial. Fixes #183

---

TerminalDocs/tutorials/tab-title.md

"E.g." seems to be the intended meaning: There are Linux distributions that are not Ubuntu, but Ubuntu is an example of a Linux distribution for which the behavior is the given.

Fix a typo in discussion of terminal titles

---

TerminalDocs/tutorials/powerline-setup.md

Currently, the install recommends using an out-of-date version of golang, which in turn causes issues while installing powerline-go.
Suggest users use the PPA for updating golang, as suggested by 
Install the binary version of powerline-go:
```bash
mkdir -o ~/.bin/
wget https://github.com/justjanne/powerline-go/releases/latest/download/powerline-go-linux-amd64 -O ~/.bin/.powerline-go
chmod a+x ~/.bin/powerline-go
```
This would in turn require an updated snippet:
```bash
function _update_ps1() {
PS1="$($HOME/.bin/powerline-go -error $?)"
}
if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ]; then
PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```

Powerline on old Ubuntu: Use up-to-date version of golang

---

TerminalDocs/customize-settings/startup.md

See microsoft/terminal#9036
When set to `true`, the terminal window will auto-center itself on the display it opens on. The terminal will use the `"initialPosition"` to determine which display to open on.
This interacts with the other launch settings in the following ways:
* `"initialPos": x,y`, `"centerOnLaunch": true`, `"launchMode": "default"`: center on the monitor that `x,y` is on.
* `"initialPos": x,y`, `"centerOnLaunch": true`, `"launchMode": "maximized"`: maximized on the monitor that `x,y` is on (`centerOnLaunch` adds nothing).
* `"initialPos": <omitted>`, `"centerOnLaunch": true`, `"launchMode": "default"`: center on the default monitor.
* `"initialPos": <omitted>`, `"centerOnLaunch": true`, `"launchMode": "focus"`: center and enter focus mode on the default monitor.
* …

Add docs for centerOnLaunch

---

TerminalDocs/customize-settings/startup.md

See original PR: microsoft/terminal#9118
> ## Windowing Behavior
> 
> This setting controls how new terminal instances attach to existing windows. This propoerty is only used if the `--window,-w window` commandline argument is not provided. This setting accepts the following possible values:
> 
> * `useNew`: Create a new window, always. This is how the Terminal always behaved prior to version 1.7.
> * `useExisting`: Create new tabs in the most recently used window on this desktop. If there's not an existing window on this virtual desktop, then create a new Terminal window.
> * `useAnyExisting`: Create new tabs in the most recently used window, regardless of which virtual desktop the window is on.
> 
> **Property name:** `windowingBehavior`
> 
> **Necessity:** Optional
> 
> **Accepts:** …

Add docs for windowing behavior

---

TerminalDocs/customize-settings/actions.md

See https://github.com/microsoft/terminal/pull/9208

Add docs for `newWindow` action

---

TerminalDocs/tutorials/powerline-setup.md

Updated the docs to be correct for oh-my-posh V3 on Windows and introduce it for Ubuntu WSL as V3 now also runs cross platform (same prompt regardless of where you want to work).

refactor(powerline): update for oh-my-posh V3

---

TerminalDocs/tutorials/tab-title.md

See also at issue https://github.com/MicrosoftDocs/terminal/issues/122
Closes #122

Improved title setting procedure on bash/Ubuntu so that it doesn't destroy `PS1`

---

TerminalDocs/TOC.yml
TerminalDocs/command-line-arguments.md
TerminalDocs/command-palette.md
TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/appearance.md
TerminalDocs/customize-settings/color-schemes.md
TerminalDocs/customize-settings/interaction.md
TerminalDocs/customize-settings/profile-advanced.md
TerminalDocs/customize-settings/profile-appearance.md
TerminalDocs/customize-settings/profile-general.md
TerminalDocs/customize-settings/rendering.md
TerminalDocs/customize-settings/startup.md
TerminalDocs/json-fragment-extensions.md
TerminalDocs/new-terminal-arguments.md
TerminalDocs/panes.md
TerminalDocs/search.md
TerminalDocs/troubleshooting.md
TerminalDocs/tutorials/powerline-setup.md
TerminalDocs/tutorials/ssh.md
TerminalDocs/tutorials/tab-title.md

All of the docs updates for the 1.7 release.

Merge release 1.7 into master

---

TerminalDocs/TOC.yml
TerminalDocs/command-line-arguments.md
TerminalDocs/command-palette.md
TerminalDocs/custom-terminal-gallery/custom-schemes.md
TerminalDocs/custom-terminal-gallery/frosted-glass-theme.md
TerminalDocs/custom-terminal-gallery/powerline-in-powershell.md
TerminalDocs/custom-terminal-gallery/raspberry-ubuntu.md
TerminalDocs/custom-terminal-gallery/retro-command-prompt.md
TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/appearance.md
TerminalDocs/customize-settings/color-schemes.md
TerminalDocs/customize-settings/interaction.md
TerminalDocs/customize-settings/profile-advanced.md
TerminalDocs/customize-settings/profile-appearance.md
TerminalDocs/customize-settings/profile-general.md
TerminalDocs/customize-settings/rendering.md
TerminalDocs/customize-settings/startup.md
TerminalDocs/get-started.md
TerminalDocs/index.md
TerminalDocs/json-fragment-extensions.md
TerminalDocs/new-terminal-arguments.md
TerminalDocs/panes.md
TerminalDocs/search.md
TerminalDocs/troubleshooting.md
TerminalDocs/tutorials/powerline-setup.md
TerminalDocs/tutorials/ssh.md
TerminalDocs/tutorials/tab-title.md

This PR includes the updates for the 1.7 release

Merge master into live

---

TerminalDocs/troubleshooting.md

We probably get at least one open issue about this a month. If it's in the docs, maybe we'd get fewer?

Add a FAQ entry for folks who are confused when Settings does nothing

---

TerminalDocs/tips-and-tricks.md

Addresses issue https://github.com/MicrosoftDocs/terminal/issues/6

Add mouse interaction section

---

TerminalDocs/command-line-arguments.md

document how to start windows terminal and have it execute a command

---

TerminalDocs/customize-settings/interaction.md

Documentation for https://github.com/microsoft/terminal/pull/9807

Document trimBlockSelection setting

---

TerminalDocs/customize-settings/profile-appearance.md

Updates documentation for how the font settings should be defined

Update docs with new font struct

---

TerminalDocs/get-started.md

Select Settings in the dropdown menu will open the Settings UI instead of open file since the release version v1.6.10571.0
But this page is not up to date, so I edit it.

Update configuration section of get-start

---

TerminalDocs/customize-settings/interaction.md

Add experimental.input.forceVT setting to the interaction page

---

TerminalDocs/customize-settings/actions.md

Added support for browser media keys in the action keybinding: https://github.com/microsoft/terminal/pull/10801

Added browser media keys

---

TerminalDocs/customize-settings/profile-appearance.md

See https://github.com/microsoft/terminal/pull/10759

add intenseTextStyle to the docs

---

TerminalDocs/panes.md

Documentation for 
- https://github.com/microsoft/terminal/pull/10713
- https://github.com/microsoft/terminal/pull/10638
- https://github.com/microsoft/terminal/pull/10780
- https://github.com/microsoft/terminal/pull/10927
I am absolutely not a technical writer, please feel free to redo everything to make it coherent and approachable. I also don't know how the gifs were created so I'll leave that to someone else as well.

Multiple new pane features

---

TerminalDocs/command-line-arguments.md

Just updated the store version of Windows Terminal and the --window argument now works for naming windows, and targeting them.

wt.exe --window argument now available

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/interaction.md

While the `MinimizeToTray` and `AlwaysShowTrayIcon` global settings have merged, I took out the `MinimizeToTray` action from the original PR in order to put it in its own PR for more discussion. This PR just removes the bits that mention the action.

Remove MinimizeToTray action mentions

---

TerminalDocs/customize-settings/profile-appearance.md
TerminalDocs/tips-and-tricks.md

Docs https://github.com/microsoft/terminal/pull/11180
Most of the diff is due to me flipping the order of these sections.

Opacity docs

---

TerminalDocs/install.md

Adds a small tip that explains how to modularize configuration files using JSON fragment extensions.
Closes #423

Add tip on extensions for configuration files

---

TerminalDocs/tutorials/custom-prompt-setup.md

When using winget, Oh-my-posh will not add Set-PoshPrompt to path, the execution will fail. The correct configuration can be found in https://ohmyposh.dev/docs/windows#replace-your-existing-prompt

Correct $PROFILE configuration

---

TerminalDocs/dynamic-profiles.md

DocuTune: Fix ms.topic values
Note the following:
- DocuTune drives improved quality of technical content by finding and automatically correcting a broad set of issues in Markdown and YAML files. DocuTune performs these updates intelligently, only making corrections in the sections of a document where the correction is suitable.
- DocuTune PRs often standardize spacing, formatting, and casing of Markdown elements to support the DocuTune onboarding process.
- DocuTune PRs might contain other minor edits noticed during a manual review.
- DocuTune PRs might include files whose Acrolinx score was below the target threshold prior to this PR.
- Delimiters such as asterisks and backticks may be added to link descriptions or alt-text to denote UI elements or other string literals that should not …

DocuTune: Fix ms.topic values

---

TerminalDocs/command-palette.md
TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/appearance.md
TerminalDocs/customize-settings/color-schemes.md
TerminalDocs/customize-settings/interaction.md
TerminalDocs/customize-settings/profile-advanced.md
TerminalDocs/customize-settings/profile-appearance.md
TerminalDocs/customize-settings/profile-general.md
TerminalDocs/customize-settings/rendering.md
TerminalDocs/customize-settings/startup.md
TerminalDocs/index.md
TerminalDocs/install.md
TerminalDocs/samples.md
TerminalDocs/tips-and-tricks.md
TerminalDocs/troubleshooting.md

This is a bulk fix - According to the new DevRel GX group mission, the Localization production team drives the localization priority and translation quality per customer usage data, e.g. Page View or MAU of the language. The localization priority is defined by the project setting in localization pipeline - ms.localizationpriority in the source file is no longer used as a driving parameter to define the localization priority. https://review.docs.microsoft.com/help/contribute/localization-checklist-for-writer?branch=master#stop-using-mslocalizationpriority-metadata

Bulk fix - Removing .localizationpriority

---

TerminalDocs/tutorials/new-tab-same-directory.md

"it's" should be "its" because it wouldn't make sense otherwise.

style: fix typo in new-tab-same-directory.md

---

TerminalDocs/customize-settings/actions.md

As in https://github.com/microsoft/terminal/pull/10906
This action can be used to manually clear the Terminal buffer. This is useful for scenarios where you're not sitting at a command-line shell prompt and can't easily run `Clear-Host`/`cls`/`clear`.
**Command name:** `clearBuffer`
**Default bindings:**
```json
{ "command": { "action": "clearBuffer", "clear": "all" } },
```
| Name | Necessity | Accepts | Description |
| ---- | --------- | ------- | ----------- |
| `clear` | Optional | `"screen"`, `"scrollback"`, `"all"` | What part of the screen to clear. <ul><li>`"screen"`: Clear the terminal viewport content. Leaves the scrollback untouched. Moves the cursor row to the top of the viewport (unmodified).</li><li>`"scrollback"`: Clear the scrollback. Leaves the viewport …

Add the `clearBuffer` action which is in 1.12

---

TerminalDocs/customize-settings/actions.md

from https://github.com/microsoft/terminal/pull/12092
⚠️ This might need to go into the 1.13 branch ⚠️ 
This changes the opacity of the window. If `relative` is set to true, it will adjust the opacity relative to the current opacity. Otherwise, it will set the opacity directly to the given `opacity`
**Command name:** `adjustOpacity`
**Default bindings:**
```json
{ "command": { "action": "adjustOpacity", "relative": false, "opacity": 0 } },
{ "command": { "action": "adjustOpacity", "relative": false, "opacity": 25 } },
{ "command": { "action": "adjustOpacity", "relative": false, "opacity": 50 } },
{ "command": { "action": "adjustOpacity", "relative": false, "opacity": 100 } }
```
| Name | Necessity | Accepts | Description |
| ---- | --------- | ------- | ----------- |
| `opacity` | …

add `adjustOpacity` 

---

TerminalDocs/customize-settings/actions.md

From https://github.com/microsoft/terminal/pull/12097
This allows the user to export the text of the buffer to a file. If the file doesn't exist, it will be created. If the file already exists, its contents will be replaced with the Terminal buffer text.
**Command name:** `exportBuffer`
**Default bindings:**
```json
{ "command": { "action": "exportBuffer" } },
```
| Name | Necessity | Accepts | Description |
| ---- | --------- | ------- | ----------- |
| `path` | Optional | String | If provided, then the Terminal will export the buffer contents to the given file. Otherwise, the Terminal will open a file picker to choose the file to export to. |
> [!IMPORTANT]
> This feature is only available in [Windows Terminal Preview](https://aka.ms/terminal-preview).

Add `exportBuffer` action (1.13)

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/profile-general.md
TerminalDocs/faq.yml

documents https://github.com/microsoft/terminal/pull/12137
references [#1032 - Elevation Quality of Life Improvements.md](https://github.com/microsoft/terminal/blob/main/doc/specs/%235000%20-%20Process%20Model%202.0/%231032%20-%20Elevation%20Quality%20of%20Life%20Improvements.md#background)
Closes https://github.com/microsoft/terminal/issues/12309

Docs for `elevate`

---

TerminalDocs/customize-settings/profile-advanced.md

Looks like we forgot to document `bellSound` for the 1.13 release.
Implemented here: https://github.com/microsoft/terminal/pull/11511

Add `bellsound` profile setting

---

TerminalDocs/tutorials/custom-prompt-setup.md

#504 
The `Get-PoshThemes` command no longer exists, updated the step to point users to the themes doc page.

Change step to view themes on documentation site

---

.gitattributes
TerminalDocs/troubleshooting.md

Hi!
This is a PR that tries to clean up the "Set your WSL distribution to start in the home `~` directory when launched" section of the troubleshooting guide, following what I noticed in https://github.com/MicrosoftDocs/terminal/pull/455#issuecomment-1014865087. 
I also added the `diff` attribute for Markdown files in `.gitattributes` as an addon bonus :)
Full commit messages follow:
6dfd63f
~~~
troubleshooting: Linux paths support in 'startingDirectory' was added in 1.11.2921.0
In 7cd48bc (startingDirectory path for WSL no longer requires prefix,
2022-01-07), the "Set your WSL distribution to start in the home
directory" section of the troubleshooting guide was updated to mention
that WSL paths can now be directly referenced, following
microsoft/terminal@a2a6050 (When launching wsl, …

troubleshooting: clarify WSL `startingDirectory` entry

---

TerminalDocs/tutorials/new-tab-same-directory.md

Add documentation for zsh regarding the [new tab same directory](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory#wsl) feature.
I've tried to keep it similar to the `bash` section just above.

New tab same directory (zsh)

---

TerminalDocs/command-palette.md

The example for iterable commands combines an iterable command with a
nested command. Without reading the section about nested commands, it's
not immediately obvious that these are separate concepts.
Change the example for the iterable command so that it does not also use
a nested command.
Add a second, separate example that shows combining nested and iterable
commands.
---
This was not obvious to me and @zadjii-msft helped me get it right in  https://github.com/microsoft/terminal/issues/7016#issuecomment-1040374320, so I thought I could tweak the docs a little.
---
For discoverability:
* Version Independent ID: ea47990e-361e-5a4e-1b6e-1a3969cf4653

command-palette: simplify example for iterable commands

---

TerminalDocs/tutorials/new-tab-same-directory.md

Noticed and fixed by @tomasorti at https://github.com/microsoft/terminal/issues/3158#issuecomment-1036723763.

Quoted the env-var for `setx PROMPT`

---

TerminalDocs/command-line-arguments.md

Updated --title documentation to specify behavior is specific to panes rather than tabs

---

TerminalDocs/json-fragment-extensions.md

Windows Terminal expects the 'guid' property of a profile in the
so-called "registry format" [1], i.e. enclosed in curly brackets.
The different GUID examples in TerminalDocs/json-fragment-extensions.md
are enclosed in curly brackets, but the Python script example to
generate GUIDs prints them without the enclosing curly brackets.
Use a Python f-string to print them enclosed in curly brackets.
[1] https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#unique-identifier
---
version-independent id: "341f8755-2701-601f-5b91-98527354b3e8"

json-fragment-extensions: output GUIDs in "registry format"

---

TerminalDocs/tutorials/custom-prompt-setup.md

the powershell module is deprecated, meaning you can no longer use
`Install-Module oh-my-posh` to get started. The advised way to get
started is now winget
additionally, some link in the oh-my-posh documentation changed so
I made sure to fix those as well along the way
resolves #535 
resolves #538 
resolves #532

fix(powerline): adjust docs to reflect oh-my-posh changes

---

TerminalDocs/customize-settings/actions.md

For some reason, the arguments section in the Actions page was named "actions". This doesn't really make any sense. So I renamed them to "parameters".

Rename 'actions' in actions page to 'parameters'

---

TerminalDocs/customize-settings/actions.md

`updateSelection` was never added to Windows Terminal. As such, this entire section should be removed.

Remove 'updateSelection'

---

TerminalDocs/customize-settings/profile-advanced.md

Documents the `experimental.connection.passthroughMode` profile setting introduced in https://github.com/microsoft/terminal/pull/11264

Document `experimental.connection.passthroughMode`

---

TerminalDocs/customize-settings/appearance.md

Document `experimental.useBackgroundImageForWindow` from https://github.com/microsoft/terminal/pull/12893

Document `useBackgroundImageForWindow`

---

TerminalDocs/tutorials/new-tab-same-directory.md

Adds missing code block closing backticks on line 101 which was causing the following sections to render incorrectly.

Add missing code block closing backticks

---

TerminalDocs/selection.md

Document that in mark mode you can now tab to the next/previous hyperlink.

Document tabbing to hyperlink

---

README.md
TerminalDocs/command-line-arguments.md

**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

[BULK UPDATE] DocuTune - Rebranding links

---

TerminalDocs/customize-settings/appearance.md

Adds missing `:::column-end::: :::row-end:::` after `Show close all tabs popup` so that `Use a background image for the entire window` takes the whole line and not only the right part of it.

Fixes position of `Use a background image for the entire window`

---

TerminalDocs/tutorials/new-tab-same-directory.md

This will help print the current working directory correctly if it has a space in its name. It was previously stated on line 109 in the WSL example.

Add double quotes to $PWD on line 148

---

TerminalDocs/command-line-arguments.md

The example for the colorscheme command was missing the escape backtick in front of the command separator.

Fix missing escape in Powershell example

---

TerminalDocs/docfx.json

@nguyen-dows @mattwoj  could you please help to merge this metadata change (adobe-target=true) to main branch and then to live? This is to enable A/B testing ability across many url base paths so we can improve Learn user experience based on data-driven decisions. This meta (adobe-target) itself will not change how your content is displayed or modify any other UI behaviors so it is safe to merge.

add the adobe-target metadata for A/B testing

---

TerminalDocs/customize-settings/actions.md

Removing the enable and disable read-only mode docs until that feature goes in a future release. These will go live once the feature is live. For now, I will exclude them from main. 
Those changes with the `enableReadOnlyMode` and `disableReadOnlyMode` docs are now saved in the `release-1.18` branch: https://github.com/MicrosoftDocs/terminal/tree/release-1.18 
These will go live once the feature is live.

Removing enableReadOnlyMode and disableReadOnlyMode docs until it goes in a future release

---

TerminalDocs/customize-settings/profile-advanced.md

Added maximum history size to the History Size docs as per: https://github.com/MicrosoftDocs/terminal/issues/510
The maximum history size is 32767 (which is similar to the value of `SHRT_MAX`)

Added maximum history size

---

TerminalDocs/customize-settings/actions.md

Addresses #662 
This PR removes instances of "Preview" from features that should be in the latest stable version of Terminal.
Note: Most of the features that were marked as "Preview" in this doc were in 1.15 such as:
- Scroll Marks: https://github.com/microsoft/terminal/pull/12948 
- Toggle Block Selection: https://github.com/microsoft/terminal/pull/13219
After this PR is merged into `main`, I will merge it to `live`

Update Actions documentation

---

TerminalDocs/panes.md

This PR remove `enableReadOnlyMode` and `disableReadyOnlyMode` docs in `panes.md` until it goes live in a future release. 
Those docs have already been saved in a [release branch](https://github.com/MicrosoftDocs/terminal/blob/release-1.18/TerminalDocs/panes.md#marking-a-pane-as-read-only) (`release-1.18`) so all we need to do is remove them from `main`.

Remove enableReadOnlyMode and disableReadyOnlyMode docs in panes

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/themes.md
TerminalDocs/panes.md

This PR adds the below preview text to instances of `enableReadOnlyMode` and `disableReadOnlyMode` in our docs (specifically in `actions.md` and `panes.md`)
```
`> [!IMPORTANT]
> This feature is only available in [Windows Terminal Preview](https://aka.ms/terminal-preview).
```
This PR also adds the below preview text to the `activeOnly` value for the 'showCloseButton' property in `TerminalDocs/customize-settings/themes.md`.
```
> [!IMPORTANT]
> The `"activeOnly"` value is only available in [Windows Terminal Preview](https://aka.ms/terminal-preview).
```
Lastly, this PR re-adds the missing `enableReadOnlyMode` docs in `TerminalDocs/customize-settings/actions.md` that was accidentally removed in PR #660

Add preview text and re-add missing enableReadOnlyMode docs

---

TerminalDocs/tutorials/shell-integration.md

The pwsh example for the shell integration does not report an error code once `$LastExitCode` is set to 0.
Try:
```
PS > cmd /c exit 0
PS > a
```
This PR fixes this issue by detecting external command errors using the history and the `$Error` variable.

Fix LastExitCode handling in the shell integration pwsh sample

---

TerminalDocs/tutorials/new-tab-same-directory.md

PSReadLine cuts a substring since the last non-whitespace character in the prompt as the error prompt [1], which is displayed when there are syntax errors. As a result, when the prompt ends in `$([char]27)\`, as in the previous example, an unexpected backslash may appear.
See: https://github.com/PowerShell/PSReadLine/issues/3719
[1] https://github.com/PowerShell/PSReadLine/blob/v2.2.6/PSReadLine/ReadLine.cs#L819.
---
Closes https://github.com/MicrosoftDocs/terminal/issues/597

Update the PowerShell example to work around a PSReadLine issue

---

TerminalDocs/tutorials/tab-title.md

It doesn't ignore quotes, but incorporates them into the new title.
The following command:
```batchfile prompt
> title "New Title"
```
will set the shell's title to `"New Title"`. A better alternative:
```batchfile prompt
> (title^ New Title)
```
Though this might be too arcane for the purposes of that document.

Fix Command Prompt's `title` usage in tab-title.md

---

TerminalDocs/breadcrumb/toc.yml
TerminalDocs/docfx.json

This PR brings breadcrumb implementation into alignment with [platform architecture requirements](https://review.learn.microsoft.com/en-us/help/platform/navigation-overview?branch=main#requirements-for-content-ecosystems). This PR is part of a previously announced batch of breadcrumb fixes across the Learn platform and will be auto-merged if there are no build warnings. This PR may include removing the “extend breadcrumb” feature from any docfx files that are still using it, fixing breadcrumb file references in the docfx file, and rewriting breadcrumb files to match the [approved breadcrumb pattern](https://review.learn.microsoft.com/en-us/help/platform/navigation-breadcrumbs-overview?branch=main#breadcrumbs-in-documentation) for a given product’s documentation.

Fix breadcrumbs

---

TerminalDocs/customize-settings/appearance.md

- Fixed `type` from `matchProfile` to `matchProfiles`
- Added a note about using `source` as property for matching (after wasting about an hour trying to make it work...)

Fix type name and add some info

---

TerminalDocs/dynamic-profiles.md

The values for cmder and Cygwin have changed,
- Cygwin is normally installed into "C:\cygwin64" instead of "C:\Cygwin"
- cmder json commandline doesn't need the ' " ' after ' /k '
Thank-You :)

Update  'cmder' & 'Cygwin' dynamic-profiles.md

---

TerminalDocs/command-line-arguments.md

There were already a few of these notes in the page, so I just went ahead and added them to any other PowerShell examples that use a semicolon.
Closes #763

Add more notes to escape semicolons in PowerShell

---

TerminalDocs/customize-settings/profile-general.md

FIXES #768
There is currently no documentation about "profile index" and actually how to adjust this or what affects it.  The "profile index" directly affects the key combo to launch, such as Ctrl+Shift+1
- This helps tell users how to adjust the index numbering, and hence control the assigned key combo to launch.

Add note about Profile index adjustments

---

TerminalDocs/customize-settings/interaction.md
TerminalDocs/customize-settings/profile-appearance.md

Added Enable Unfocused Acrylic Global Setting 
Updated Opacity and Acrylic. 
No more OS limitations!
https://github.com/microsoft/terminal/pull/15974

Update Doc for Unfocused Acrylic and Opacity 

---

TerminalDocs/tutorials/new-tab-same-directory.md

This pull request addresses an issue in the Windows Terminal documentation tutorial for creating new tabs in the same directory within the WSL Ubuntu environment. The provided code snippet, when added to the end of `.bashrc`, results in a syntax error if any plugins that altered `PROMPT_COMMAND` were sourced earlier, such as `pyenv` or `rupa/z`.
When following the documentation and adding the following code to `.bashrc`:
```sh
PROMPT_COMMAND=${PROMPT_COMMAND:+"$PROMPT_COMMAND; "}'printf "\e]9;9;%s\e\\" "$(wslpath -w "$PWD")"'
```
It results in the following error:
```sh
-bash: PROMPT_COMMAND: line 1: syntax error near unexpected token `;;'
-bash: PROMPT_COMMAND: line 1: `(_z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null &);; printf "\e]9;9;%s\e\\" "$(wslpath -w "$PWD")"' # 
```
This …

Fix Syntax Error in Windows Terminal Documentation for Duplicating Tabs in Bash Shell on WSL

---

TerminalDocs/tutorials/shell-integration.md

I was yesterday years old when I actually set up oh-my-posh for the first time. Sorry for being a persistent cmd user

Add notes for how to do shell integration with oh-my-posh

---

TerminalDocs/tutorials/new-tab-same-directory.md

The docs mention using a specific escape sequence, but they don't mention the name.
I've added a mention to OSC 9;9 as often shell themes / tools refer to the escape sequence by name. This gives users trying to enable this feature in their tools something to search for.

Update new-tab-same-directory.md to mention OSC 9;9

---

TerminalDocs/customize-settings/profile-general.md

how to run a batch file for cmd.exe

add example to commandline value

---

TerminalDocs/customize-settings/appearance.md

Adds documentation about the new icon override feature for profile and action entries to be introduced by PR: https://github.com/microsoft/terminal/pull/18116
Also added a section on "action" entries as it was previously missing.

Added icon override documentation to appearance.md

---

TerminalDocs/customize-settings/appearance.md

Adds documentation for a new "showTabsFullscreen" setting to be introduced by PR: https://github.com/microsoft/terminal/pull/18171

Add "showTabsFullscreen" setting to documentation

---

TerminalDocs/distributions.md

Add a FAQ section to the Portable Mode docs and address https://github.com/MicrosoftDocs/terminal/issues/665

Add FAQ section to Portable Mode Docs

---

TerminalDocs/tutorials/progress-bar-sequences.md

The BEL character seems to have been accidentally removed somewhere down the line. I restored it from the original version of the file.

Add back accidentally-deleted BEL character
