MicrosoftDocs/terminal

TerminalDocs/command-line-arguments.md
TerminalDocs/index.md

Please take a look and let me know if I'm off on my re-writes.

Changes to overview and command line arguments txt

---

TerminalDocs/tutorials/powerline-setup.md

Updates related to [User Story 1720891](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1720891).

1720891, fix unicode character

---

TerminalDocs/tutorials/ssh.md

Resolving ask in issue https://github.com/MicrosoftDocs/terminal/issues/25

Add specify start director for ssh

---

README.md
ThirdPartyNotices.md

chore: Cleanup MS Links

---

TerminalDocs/customize-settings/key-bindings.md

All these settings got missed at one time or another. 
* `renameTab` was a community contribution. 
* The other 3 were probably just me being lazy.

Add: `toggleRetroEffect`, `renameTab`, `setTabColor`, `openColorPicker`

---

TerminalDocs/command-line-arguments.md
TerminalDocs/customize-settings/global-settings.md
TerminalDocs/customize-settings/key-bindings.md
TerminalDocs/customize-settings/profile-settings.md
TerminalDocs/panes.md
TerminalDocs/tips-and-tricks.md

- Fix up wording on the new 1.2 features.
- Remove preview labels from 1.1 features.

Fix up 1.2 release branch

---

TerminalDocs/customize-settings/key-bindings.md

- Add MENU key with "menu" "app" as key bindings.

Added MENU key binding.

---

TerminalDocs/customize-settings/global-settings.md
TerminalDocs/customize-settings/key-bindings.md

Docs for microsoft/terminal#6004

Add enhanced copyFormatting

---

TerminalDocs/customize-settings/key-bindings.md

⚠️ **THERE'S NO 1.3 BRANCH YET GUYS** - @cinnamon-msft please feel free to re-target this PR when one gets made
This is the documentation for microsoft/terminal#6993 - the `setColorScheme` action.

Add a doc for `setColorScheme`

---

TerminalDocs/TOC.yml
TerminalDocs/custom-terminal-gallery/custom-schemes.md
TerminalDocs/customize-settings/color-schemes.md

Added a little more details on how to use the color schemes, but also an invitation to sharing via twitter. Be nice to have more!
Fixes #55 
Fixes #129 
Fixes #130

Added some more details on creating color schemes with examples

---

TerminalDocs/customize-settings/profile-settings.md

Fix slashes in WSL starting directory tip

---

TerminalDocs/customize-settings/global-settings.md
TerminalDocs/customize-settings/profile-settings.md

🔔 **THERE'S NO `release-1.5` BRANCH YET** 🔔 @cinnamon-msft make sure to fix this before merge
This adds the documentation for the `bellStyle` property, as added in microsoft/terminal#7793

Add docs for bell style

---

TerminalDocs/command-line-arguments.md
TerminalDocs/customize-settings/global-settings.md

This PR documents new launch mode values introduced in https://github.com/microsoft/terminal/pull/7873 to address https://github.com/microsoft/terminal/issues/7124.
Not sure what is the correct contribution procedure for such changes. Hence, opening this change as a draft PR to master (please do not merge 😄 )

7124: add documentation for the new launch modes

---

TerminalDocs/customize-settings/actions.md

Document `openTabRenamer` action
https://github.com/microsoft/terminal/pull/6567

Add docs for 'openTabRenamer' action

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/profile-settings.md
TerminalDocs/troubleshooting.md

Icons are supported in actions and profiles.  As of https://github.com/microsoft/terminal/pull/7830, emoji are supported for profiles too.

Update icon support

---

TerminalDocs/customize-settings/interaction.md

Originally filed by Andrewery https://github.com/MicrosoftDocs/terminal/pull/134/files

Add note about escaping characters with backslash

---

TerminalDocs/customize-settings/profile-general.md

As originally submitted by @aloneguid in https://github.com/MicrosoftDocs/terminal/pull/135

Add icon example and folder location

---

TerminalDocs/customize-settings/interaction.md

Original submission: https://github.com/MicrosoftDocs/terminal/pull/134/files

Fix default value by escaping characters

---

TerminalDocs/customize-settings/profile-general.md

...from PR https://github.com/MicrosoftDocs/terminal/pull/181

Add backslash escape note

---

TerminalDocs/customize-settings/profile-advanced.md

migrated from PR https://github.com/MicrosoftDocs/terminal/pull/199/files

Add guid command for powershell

---

TerminalDocs/custom-terminal-gallery/custom-schemes.md
TerminalDocs/custom-terminal-gallery/frosted-glass-theme.md
TerminalDocs/custom-terminal-gallery/powerline-in-powershell.md
TerminalDocs/custom-terminal-gallery/raspberry-ubuntu.md
TerminalDocs/custom-terminal-gallery/retro-command-prompt.md
TerminalDocs/index.md

@mattwojo 
**Summary:** Page title update for those title who exceeded 60 characters. Please feel free to edit :)
URL | Current Page   Title | Characters | SEO Page Title | Characters (under 60 Recommended)
-- | -- | -- | -- | --
https://docs.microsoft.com/en-us/windows/terminal/ | Windows   Terminal overview \| Microsoft Docs | 42 | An   overview on Windows Terminal \| Microsoft Docs | 48
https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/custom-schemes | Custom   Color Schemes guide \| Microsoft Docs | 43 | Windows   terminal Custom Color Schemes guide \| Microsoft Docs | 60
https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/powerline-in-powershell | Windows   Terminal Powerline in PowerShell Configuration \| Microsoft Docs | 71 | Windows …

SEO: Page_title_updates

---

TerminalDocs/customize-settings/interaction.md

Documentation for https://github.com/microsoft/terminal/pull/8965

Document Focus-Follow-Mouse setting

---

TerminalDocs/index.md

Fix a minor typo with the default keybinding for new tab

---

TerminalDocs/command-line-arguments.md

Add a note that --window is only available in 1.7+

---

TerminalDocs/customize-settings/appearance.md

Fix a typo in this doc

---

TerminalDocs/tips-and-tricks.md

Add a note that you can't set the tab color from the commandline

---

TerminalDocs/command-line-arguments.md
TerminalDocs/customize-settings/actions.md

Documentation for the changes  introduced in https://github.com/microsoft/terminal/pull/9392

Document suppressApplicationTitle

---

TerminalDocs/command-line-arguments.md
TerminalDocs/customize-settings/actions.md

Add docs for microsoft/terminal#9602

Add docs for `--colorScheme`

---

TerminalDocs/custom-terminal-gallery/custom-schemes.md

https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/custom-schemes
#PingMSFTDocs

Typo "Windows terminal"→"Windows Terminal"

---

TerminalDocs/get-started.md

Resolves https://github.com/MicrosoftDocs/terminal/pull/286

Add link to alternative install options

---

TerminalDocs/customize-settings/profile-appearance.md

Documentation update for microsoft/terminal#9386

Update `cursorHeight` minimum value

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/interaction.md

Adds documentation for:
- MinimizeToTray Action
- MinimizeToTray global setting
- AlwaysShowTrayIcon global setting

Documentation for Minimize To Tray settings

---

TerminalDocs/customize-settings/actions.md

As implemented in microsoft/terminal#10447

Add documentation for closing tabs by index

---

TerminalDocs/get-started.md

Add note about opening command palette via dropdown menu

---

TerminalDocs/customize-settings/actions.md

Added in https://github.com/microsoft/terminal/pull/11143

Add quit action

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/panes.md

Added in https://github.com/microsoft/terminal/pull/11145

Add directional splits

---

TerminalDocs/customize-settings/actions.md

Added in [#11086](https://github.com/microsoft/terminal/pull/11086)

Add default keybinding for openSystemMenu

---

TerminalDocs/panes.md

Add a note about the command palette to this doc

---

TerminalDocs/customize-settings/color-schemes.md

Add details about the command used to print the table

---

TerminalDocs/customize-settings/startup.md

initialPos -> initialPosition

---

TerminalDocs/json-fragment-extensions.md

The LocalAppData path was missing `{app-name}`

Corrected path

---

TerminalDocs/tips-and-tricks.md

Make this statement a little more specifc.

Minor quake mode text update

---

TerminalDocs/customize-settings/interaction.md

From https://github.com/microsoft/terminal/pull/11473
Closes https://github.com/microsoft/terminal/issues/11642

add `trimPaste` to the docs

---

TerminalDocs/faq.yml

Set ms.topic: faq where YamlMime:FAQ
Note the following:
- DocuTune drives improved quality of technical content by finding and automatically correcting a broad set of issues in Markdown and YAML files. DocuTune performs these updates intelligently, only making corrections in the sections of a document where the correction is suitable.
- DocuTune PRs often standardize spacing, formatting, and casing of Markdown elements to support the DocuTune onboarding process.
- DocuTune PRs might contain other minor edits noticed during a manual review.
- DocuTune PRs might include files whose Acrolinx score was below the target threshold prior to this PR.
- Delimiters such as asterisks and backticks may be added to link descriptions or alt-text to denote UI elements or other string literals that …

Set ms.topic: faq where YamlMime:FAQ

---

TerminalDocs/tutorials/ssh.md

Changed a reference to Windows 10 to general Windows
> This PR is part of my effort to bring all Microsoft Docs to Windows 11. You can see my overall progress in [this gist](https://gist.github.com/Aaron-Junker/ad8f6234f1a991e46e234b25dc0ce0dc)

Very small change which updates a doc to Windows 11

---

TerminalDocs/customize-settings/actions.md

Documents the `selectAll` action from https://github.com/microsoft/terminal/pull/13045

Document `selectAll`

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/interaction.md

See title. Not pointing any fingers, but _somebody_ (\*\*cough\*\* Kayla \*\*cough\*\*) forgot to document their change.

Document changing the default value for `trimBlockSelection`

---

TerminalDocs/customize-settings/actions.md

Document behavior in https://github.com/microsoft/terminal/pull/11621
NOTE: this applies to stable _and_ preview.

Update `newTab` with note about invalid index

---

TerminalDocs/tutorials/new-tab-same-directory.md

- Added instructions for MINGW
- Added a link to this file, so it's easier to find it for people who'd like to contribue

Instructions for MINGW

---

TerminalDocs/customize-settings/actions.md

Document `expandSelectionToWord` action introduced in https://github.com/microsoft/terminal/pull/13765

Document ExpandSelectionToWord action

---

TerminalDocs/customize-settings/appearance.md

document `newTabPosition` from https://github.com/microsoft/terminal/pull/13421

document `newTabPosition`

---

TerminalDocs/tutorials/new-tab-same-directory.md

Noticed a typo in Line 143 so I thought I'd point it out.

Edit: Typo in Line 143 in `PROMPT_COMMAND`

---

TerminalDocs/command-line-arguments.md

As implemented in microsoft/terminal#13730 for inclusion in the 1.17 release.

1.17 - Add documentation for `--pos` and `--size` cmdline args

---

TerminalDocs/samples.md

**Global effort to improve metadata quality across the Learn platform**
These changes make reports cleaner, easier to use, more consistent, and more reflective of our current business. After you accept these changes and they're merged, they will be reflected in standard dashboards and reports maintained by C+E Skilling Business & Customer Success. You'll need to use new filter values in these reports, and you may need to update any custom dashboards or Kusto queries. If you have any questions, please contact Learn Platform Metadata (learn-metadata@microsoft.com).

Bulk Metadata Update - ms.topic update.

---

TerminalDocs/customize-settings/startup.md
TerminalDocs/dynamic-profiles.md
TerminalDocs/tutorials/ssh.md

This is for a PR that I'm submitting in the Terminal repo.

Add documentation for dynamic SSH profiles

---

TerminalDocs/customize-settings/profile-appearance.md

This is for a PR that I'm submitting in the Terminal repo.

Add support for scroll bar 'always' setting

---

TerminalDocs/custom-terminal-gallery/powerline-in-powershell.md

This was a change in v1.12+, see https://learn.microsoft.com/windows/terminal/customize-settings/profile-appearance#opacity

Update acrylicOpacity to opacity

---

TerminalDocs/docfx.json

_High priority PR for navigation and breadcrumb compliance_
This PR addresses required fixes to get content to basic compliance with site findability standards by 12/30/22. The progress of this effort is actively being reported to Scott Guthrie and his SLT in support of content quality initiatives.
A Pull Request has been made from the Learn Platform’s Metadata Management System. Please review and merge this Pull Request within 5 days. If you have any questions or concerns about the purpose of these metadata updates, please contact [docsmetarequests@microsoft.com](mailto:docsmetarequests@microsoft.com). If you are not the correct contact for this content and repository, please notify [Learn-Metadata-Admin@microsoft.com](mailto:Learn-Metadata-Admin@microsoft.com).
If this Pull Request is …

Add new universal Windows header

---

TerminalDocs/tutorials/custom-prompt-setup.md

Adjusted the oh-my-posh CLI interface to reflect the latest changes (even if this information is backwards compatible, it's inconsistent with the latest docs on https://ohmyposdh.dev).

fix(powerline): update oh-my-posh CLI

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/panes.md

To add context, these are to update the docs for the following issues/pr's:
https://github.com/microsoft/terminal/issues/14415
https://github.com/microsoft/terminal/pull/14995

Add documentation to include information about enable/disable read-only mode functionality

---

TerminalDocs/command-line-arguments.md
TerminalDocs/customize-settings/actions.md

Closes #638
I added the `swapPane` action, and moved `splitPane` to the top of the Panes section, since that's the most relevant thing to do

Many updates to commandline args docs, and some missing actions too

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/profile-advanced.md
TerminalDocs/customize-settings/themes.md

See https://github.com/microsoft/terminal/pull/15237 which still needs to get merged though.
So don't know when this MR needs to be merged then :-) but at least the new value is already documented.

Document 'activeOnly' value for 'showCloseButton' property.

---

TerminalDocs/tutorials/shell-integration.md

Fix typo in shell-integration.md

---

TerminalDocs/install.md
TerminalDocs/tutorials/shell-integration.md

This main to live update includes the addition of Windows 10 default terminal docs and a typo in our shell integration docs (knwo -> know)

Main to Live

---

TerminalDocs/selection.md

update: selection.md with a new copy parameter

Copy text without dismissing the selection

---

TerminalDocs/customize-settings/actions.md
TerminalDocs/customize-settings/profile-appearance.md
TerminalDocs/customize-settings/themes.md
TerminalDocs/index.md
TerminalDocs/install.md
TerminalDocs/panes.md
TerminalDocs/tips-and-tricks.md
TerminalDocs/troubleshooting.md

Remove all the 1.18 preview tags

---

TerminalDocs/customize-settings/appearance.md

Fix the rest of the matchProfile(s) to matchProfiles(s)

---

TerminalDocs/tutorials/ssh.md

Remove SSH note from the docs since it has yet to be implemented

---

TerminalDocs/faq.yml

Also a note on focus mode, cause this happens frequently
Closes #719

Add docs on where the settings file is

---

TerminalDocs/customize-settings/actions.md

As per #300. This PR also removes an old notice from Windows Terminal 1.4 (it's been many years and many releases since then!)

Document wt action

---

TerminalDocs/panes.md

Resolves https://github.com/MicrosoftDocs/terminal/issues/770

Fix alt key translation

---

TerminalDocs/customize-settings/profile-advanced.md

Document "automatic" as a value for the CloseOnExit setting

---

TerminalDocs/customize-settings/actions.md

Updates the docs page for Actions with the following changes:
- The actions examples now no longer contain keybindings
- The removed keybindings have now been moved to their own section where they refer to said actions by ID
- The list of all the available commands/actions now shows both the default ID for the in-built actions as well as their default keybindings

Update docs with changes from implementing Action IDs

---

TerminalDocs/distributions.md

Closes https://github.com/MicrosoftDocs/terminal/issues/671

Add min version to portable mode docs

---

TerminalDocs/tutorials/new-tab-same-directory.md

As per https://github.com/MicrosoftDocs/terminal/issues/819

Add missing semicolon to the bash section

---

TerminalDocs/customize-settings/profile-advanced.md

Documents the new option introduced by https://github.com/microsoft/terminal/pull/18759

Document 'mingw' path translation style
